package com.raaivan.modules.users.beans;

import com.raaivan.modules.users.util.UserUtilities;
import com.raaivan.util.PublicMethods;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope(scopeName = BeanDefinition.SCOPE_PROTOTYPE)
public class Password {
    private PublicMethods publicMethods;
    private UserUtilities userUtilities;

    @Autowired
    public void _setDependencies(PublicMethods publicMethods, UserUtilities userUtilities) {
        if (this.publicMethods == null) this.publicMethods = publicMethods;
        if (this.userUtilities == null) this.userUtilities = userUtilities;
    }

    private String _Value;
    private String _Salt;
    private String _Salted;
    private String _Encrypted;
    private Boolean AutoGenerated;

    public Password() {
        this.AutoGenerated = false;
        _Salt = userUtilities.generatePasswordSalt();
    }

    public Password(String value) {
        this.AutoGenerated = false;
        _Value = value;
        _Salt = userUtilities.generatePasswordSalt();
        _set();
    }

    private void _set() {
        _Salted = userUtilities.encodePassword(_Value, _Salt);
        _Encrypted = publicMethods.sha1(_Value);
    }

    public String getValue() {
        return _Value;
    }

    public void setValue(String value) {
        _Value = value;
        _set();
    }

    public String getSalt() {
        return _Salt;
    }

    public String getSalted() {
        return _Salted;
    }

    public String getEncrypted() {
        return _Encrypted;
    }

    public Boolean isAutoGenerated() {
        return AutoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        AutoGenerated = autoGenerated;
    }
}