spring:
  profiles: dev
  datasource:
    url: jdbc:sqlserver://localhost:53368;databaseName=EKM_App
    username: sa
    password: hrdovjshjpvjo
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  #resources:
  #  static-locations: classpath:/static/
server:
  port: 8082
  compression:
    enabled: true
  #error:
  #  whitelabel:
  #    enabled: false
---
spring:
  profiles: test
server:
  port: 8083
  compression:
    enabled: true